name: Update Markdown Files

on:
  push:
    paths:
      - "백준/**/*.cpp"
      - "백준/**/*.cs"
      - "백준/**/*.md"

jobs:
  update_md:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository를 체크아웃
      - name: Checkout the repository
        uses: actions/checkout@v3

      # 2. 푸시된 새 파일을 가져오기
      - name: Get added files
        id: added_files
        run: |
          # 새로 추가된 파일들만 가져옵니다.
          echo "ADDED_FILES=$(git diff --name-only --diff-filter=A ${{ github.event.before }} ${{ github.sha }} | tr '\n' ' ')" >> $GITHUB_ENV

      # 3. Python 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 4. MD 파일 업데이트 (새로운 파일이 있을 때만)
      - name: Update MD Files
        if: ${{ env.ADDED_FILES != '' }} # 새 파일이 있을 경우에만 실행
        run: |
          python .github/scripts/update_md.py "${{ env.ADDED_FILES }}"

      # 5. 변경 사항이 있을 경우 커밋하기
      - name: Commit changes if any
        if: ${{ env.ADDED_FILES != '' }} # 새 파일이 있을 경우에만 실행
        run: |
          # Git 설정
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # 변경된 내용이 있을 경우에만 커밋 및 푸시
          git diff --exit-code || (
            git add . && 
            git commit -m "Update Markdown files after problem solved" && 
            git push
          )
        continue-on-error: true
